Fixed misleading-indentation in yaml_parser/src/check_input_yaml.cpp
    [161/371] Building CXX object yaml_parser/CMakeFiles/yaml_parser.dir/src/check_input_yaml.cpp.o
    FAILED: yaml_parser/CMakeFiles/yaml_parser.dir/src/check_input_yaml.cpp.o
    /usr/local/bin/c++  -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I. -I../yaml_parser/inc -I/opt/ssc/include -I../exceptions/inc -I../external_data_structures/inc -I../environment_models/inc -I../yaml_parser/.. -isystem ../yaml-cpp/src -isystem ../yaml-cpp/include -isystem ../yaml-cpp/include/yaml-cpp -isystem /opt/boost/include -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -O3 -std=gnu++0x -O3 -DNDEBUG -MD -MT yaml_parser/CMakeFiles/yaml_parser.dir/src/check_input_yaml.cpp.o -MF yaml_parser/CMakeFiles/yaml_parser.dir/src/check_input_yaml.cpp.o.d -o yaml_parser/CMakeFiles/yaml_parser.dir/src/check_input_yaml.cpp.o -c ../yaml_parser/src/check_input_yaml.cpp
    ../yaml_parser/src/check_input_yaml.cpp: In function 'bool is_an_axis(const string&)':
    ../yaml_parser/src/check_input_yaml.cpp:30:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
         if ((name == "z") or (name == "z'") or (name == "z''")) return true;
         ^~
    compilation terminated due to -Wfatal-errors.
    cc1plus: all warnings being treated as errors