[dev] Fixed missing class member model_name for KtKqForceModel
[ 46%] Building CXX object observers_and_api/CMakeFiles/observers_and_api.dir/src/simulator_api.cpp.obj

In file included from D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/core/inc/Sim.hpp:18:0,
                 from D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/observers_and_api/inc/simulator_api.hpp:7,
                 from d:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/observers_and_api/src/simulator_api.cpp:3:
D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/core/inc/ControllableForceModel.hpp: In instantiation of 'ControllableForceModel::build_parser()::<lambda(const string&, const string&, const string&, const EnvironmentAndFrames&)> [with ControllableForceType = KtKqForceModel; std::string = std::basic_string<char>]':
D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/core/inc/ControllableForceModel.hpp:55:28:   required from 'struct ControllableForceModel::build_parser() [with ControllableForceType = KtKqForceModel; ControllableForceParser = std::function<boost::optional<std::tr1::shared_ptr<ControllableForceModel> >(const std::basic_string<char>&, const std::basic_string<char>&, std::basic_string<char>, const EnvironmentAndFrames&)>]::<lambda(const string&, const string&, const string&, const class EnvironmentAndFrames&)>'
D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/core/inc/ControllableForceModel.hpp:63:27:   required from 'static ControllableForceParser ControllableForceModel::build_parser() [with ControllableForceType = KtKqForceModel; ControllableForceParser = std::function<boost::optional<std::tr1::shared_ptr<ControllableForceModel> >(const std::basic_string<char>&, const std::basic_string<char>&, std::basic_string<char>, const EnvironmentAndFrames&)>]'
D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/core/inc/SimulatorBuilder.hpp:139:90:   required from 'SimulatorBuilder& SimulatorBuilder::can_parse(typename boost::enable_if<boost::is_base_of<ControllableForceModel, T> >::type*) [with T = KtKqForceModel; typename boost::enable_if<boost::is_base_of<ControllableForceModel, T> >::type = void]'
d:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/observers_and_api/src/simulator_api.cpp:62:39:   required from here
D:/Jenkins/jobs/IrtJvSimulator_Dev/workspace/code/core/inc/ControllableForceModel.hpp:58:41: error: 'model_name' is not a member of 'KtKqForceModel'
                               if (model == ControllableForceType::model_name)
                                         ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [observers_and_api/CMakeFiles/observers_and_api.dir/src/simulator_api.cpp.obj] Error 1
make[1]: *** [observers_and_api/CMakeFiles/observers_and_api.dir/all] Error 2
make: *** [all] Error 2