[hos] Added missing exception include in simulator_run.cpp
[ 91%] Building CXX object executables/CMakeFiles/xdyn.dir/src/simulator_run.cpp.obj

d:/Jenkins/jobs/XDyn_HOS/workspace/code/executables/src/simulator_run.cpp: In function 'void catch_exceptions(const std::function<void()>&, const string&)':
d:/Jenkins/jobs/XDyn_HOS/workspace/code/executables/src/simulator_run.cpp:61:31: error: expected ')' before '&' token
     catch(const ConnexionError& e)
                               ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [executables/CMakeFiles/xdyn.dir/src/simulator_run.cpp.obj] Error 1
make[1]: *** [executables/CMakeFiles/xdyn.dir/all] Error 2
make: *** [all] Error 2