[env_export] Fixed an include bug for serialization
[334/341] Building CXX object executables/CMakeFiles/xdyn-server.dir/src/InputData.cpp.o
FAILED: /usr/bin/c++   -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -std=gnu++0x -I. -I/opt/share/code/executables/inc -isystem /opt/share/code/eigen -isystem /usr/local/boost_1_60_0/include -isystem /opt/share/code/yaml-cpp/src -isystem /opt/share/code/yaml-cpp/include -isystem /opt/share/code/yaml-cpp/include/yaml-cpp -isystem /opt/share/code/base91x -isystem /opt/share/code/eigen3-hdf5 -isystem /usr/local/hdf5/include -I/opt/share/code/exceptions/inc -isystem /opt/ssc/include -I/opt/share/code/boost_program_options_descriptions/inc -I/opt/share/code/test_data_generator/inc -I/opt/share/code/external_data_structures/inc -I/opt/share/code/core/inc -I/opt/share/code/yaml_parser/inc -I/opt/share/code/external_file_formats/inc -I/opt/share/code/mesh/inc -I/opt/share/code/environment_models/inc -I/opt/share/code/binary_stl_data/inc -I/opt/share/code/force_models/inc -I/opt/share/code/parser_extensions/inc -I/opt/share/code/observers_and_api/inc -I/opt/share/code/hdb_interpolators/inc -I/opt/share/code/gz_curves/inc -I/opt/share/code/interface_hdf5/inc -MMD -MT executables/CMakeFiles/test_orbital_velocities_and_dynamic_pressures.dir/src/test_orbital_velocities_and_dynamic_pressures.cpp.o -MF executables/CMakeFiles/test_orbital_velocities_and_dynamic_pressures.dir/src/test_orbital_velocities_and_dynamic_pressures.cpp.o.d -o executables/CMakeFiles/test_orbital_velocities_and_dynamic_pressures.dir/src/test_orbital_velocities_and_dynamic_pressures.cpp.o -c /opt/share/code/executables/src/test_orbital_velocities_and_dynamic_pressures.cpp
/opt/share/code/executables/src/test_orbital_velocities_and_dynamic_pressures.cpp: In function 'int main(int, char**)':
/opt/share/code/executables/src/test_orbital_velocities_and_dynamic_pressures.cpp:83:30: error: no match for 'operator<<' (operand types are 'std::basic_ostream<char>' and 'std::vector<double>')
               << ", \"x\": " << x
                              ^
compilation terminated due to -Wfatal-errors.
ninja: build stopped: subcommand failed.
ERROR: Job failed: exit status 1