[hdf5] Fixed cast error problem detected on WinXP 32 Bits
[ 97%] Building CXX object interface_hdf5/unit_tests/CMakeFiles/interface_hdf5_tests.dir/src/h5_interface_tests.cpp.obj
In file included from c:/Jenkins/jobs/Simulator_TEST_BUILD_HDF5/workspace/code/interface_hdf5/unit_tests/src/h5_interface_tests.cpp:8:0:
C:/Jenkins/jobs/Simulator_TEST_BUILD_HDF5/workspace/code/interface_hdf5/inc/h5_interface.hpp: In instantiation of 'std::vector<T> H5_Parse<T>::Read(const H5::H5File&, const string&) [with T = PersonalInformation; std::string = std::basic_string<char>]':
C:/Jenkins/jobs/Simulator_TEST_BUILD_HDF5/workspace/code/interface_hdf5/inc/h5_interface.hpp:165:55:   required from 'std::vector<T> H5_Parse<T>::Read(const string&, const string&) [with T = PersonalInformation; std::string = std::basic_string<char>]'
c:/Jenkins/jobs/Simulator_TEST_BUILD_HDF5/workspace/code/interface_hdf5/unit_tests/src/h5_interface_tests.cpp:65:73:   required from here
C:/Jenkins/jobs/Simulator_TEST_BUILD_HDF5/workspace/code/interface_hdf5/inc/h5_interface.hpp:155:35: error: conversion to 'std::vector<PersonalInformation, std::allocator<PersonalInformation> >::size_type {aka unsigned int}' from 'hsize_t {aka long long unsigned int}' may alter its value [-Werror=conversion]
             std::vector<T> res(nnz);
                                   ^
compilation terminated due to -Wfatal-errors.
cc1plus.exe: all warnings being treated as errors
make[3]: *** [interface_hdf5/unit_tests/CMakeFiles/interface_hdf5_tests.dir/src/h5_interface_tests.cpp.obj] Error 1
make[2]: *** [interface_hdf5/unit_tests/CMakeFiles/interface_hdf5_tests.dir/all] Error 2
make[1]: *** [CMakeFiles/run_all_tests.dir/rule] Error 2
make: *** [run_all_tests] Error 2