[radiation_damping] Fixed cast error detected on Win7 MinGW 4.9.0
[ 89%] Building CXX object hdb_interpolators/unit_tests/CMakeFiles/hdb_interpolators_tests.dir/src/hdb_test.cpp.obj
c:/Jenkins/jobs/Simulator_TEST/workspace/code/hdb_interpolators/unit_tests/src/hdb_test.cpp: In function 'std::function<double(double)> get_interpolated_Br()':
c:/Jenkins/jobs/Simulator_TEST/workspace/code/hdb_interpolators/unit_tests/src/hdb_test.cpp:27:107: error: conversion to 'double' from 'size_t {aka long long unsigned int}' may alter its value [-Werror=conversion]
     auto omegas = builder.build_exponential_intervals_reversed(omega_min, omega_med, (size_t)std::floor(N*r+0.5));
                                                                                                           ^
compilation terminated due to -Wfatal-errors.
cc1plus.exe: all warnings being treated as errors
make[3]: *** [hdb_interpolators/unit_tests/CMakeFiles/hdb_interpolators_tests.dir/src/hdb_test.cpp.obj] Error 1
make[2]: *** [hdb_interpolators/unit_tests/CMakeFiles/hdb_interpolators_tests.dir/all] Error 2
make[1]: *** [CMakeFiles/run_all_tests.dir/rule] Error 2
make: *** [run_all_tests] Error 2
Build step 'Exécuter un script shell' marked build as failure