Removed unused variable in gz_curves/src/GZCurve.cpp
    [314/371] Building CXX object gz_curves/CMakeFiles/gz_curves.dir/src/GZCurve.cpp.o
    FAILED: gz_curves/CMakeFiles/gz_curves.dir/src/GZCurve.cpp.o
    /usr/local/bin/c++  -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I. -I../gz_curves/inc -I/opt/ssc/include -I../core/inc -I../exceptions/inc -I../yaml_parser/inc -I../external_data_structures/inc -I../mesh/inc -I../environment_models/inc -I../observers_and_api/inc -I../force_models/inc -I../hdb_interpolators/inc -I../test_data_generator/inc -isystem /opt/boost/include -isystem ../yaml-cpp/src -isystem ../yaml-cpp/include -isystem ../yaml-cpp/include/yaml-cpp -isystem ../eigen -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -O3 -std=gnu++0x -O3 -DNDEBUG -MD -MT gz_curves/CMakeFiles/gz_curves.dir/src/GZCurve.cpp.o -MF gz_curves/CMakeFiles/gz_curves.dir/src/GZCurve.cpp.o.d -o gz_curves/CMakeFiles/gz_curves.dir/src/GZCurve.cpp.o -c ../gz_curves/src/GZCurve.cpp
    ../gz_curves/src/GZCurve.cpp: In member function 'GZ::State GZ::Curve::get_Xeq() const':
    ../gz_curves/src/GZCurve.cpp:78:16: error: variable 'g' set but not used [-Werror=unused-but-set-variable]
         const auto g = GZ::newton_raphson(x0, pimpl->f, pimpl->k, 100, 1E-6);
                    ^
    compilation terminated due to -Wfatal-errors.
    cc1plus: all warnings being treated as errors