[hos] Removed missing-declarations option with Mingw that creates the following error
[ 40%] Building CXX object hos/CMakeFiles/hos.dir/hos.pb.cc.obj
d:/Jenkins/jobs/XDyn_HOS/workspace/code/build/hos/hos.pb.cc: In function 'void protobuf_hos_2eproto::protobuf_AssignDescriptors()':
d:/Jenkins/jobs/XDyn_HOS/workspace/code/build/hos/hos.pb.cc:487:6: error: no previous declaration for 'void protobuf_hos_2eproto::protobuf_AssignDescriptors()' [-Werror=missing-declarations]
 void protobuf_AssignDescriptors() {
      ^
compilation terminated due to -Wfatal-errors.
cc1plus.exe: all warnings being treated as errors
make[2]: *** [hos/CMakeFiles/hos.dir/hos.pb.cc.obj] Error 1
make[1]: *** [hos/CMakeFiles/hos.dir/all] Error 2
make: *** [all] Error 2
Build step 'Exécuter un script shell' marked build as failure