Fixed misleading-indentation in hdb_interpolators/src/History.cpp
    [180/371] Building CXX object hdb_interpolators/CMakeFiles/hdb_interpolators.dir/src/History.cpp.o
    FAILED: hdb_interpolators/CMakeFiles/hdb_interpolators.dir/src/History.cpp.o
    /usr/local/bin/c++  -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I. -I../hdb_interpolators/inc -I/opt/ssc/include -I../external_file_formats/inc -I../external_data_structures/inc -I../exceptions/inc -isystem /opt/boost/include -isystem ../eigen -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -O3 -std=gnu++0x -O3 -DNDEBUG -MD -MT hdb_interpolators/CMakeFiles/hdb_interpolators.dir/src/History.cpp.o -MF hdb_interpolators/CMakeFiles/hdb_interpolators.dir/src/History.cpp.o.d -o hdb_interpolators/CMakeFiles/hdb_interpolators.dir/src/History.cpp.o -c ../hdb_interpolators/src/History.cpp
    ../hdb_interpolators/src/History.cpp: In member function 'double History::interpolate_value_in_interval(size_t, double) const':
    ../hdb_interpolators/src/History.cpp:107:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
         if (std::abs(t-tB) < 1E-12) return yB;
         ^~
    compilation terminated due to -Wfatal-errors.
    cc1plus: all warnings being treated as errors