Updated HOS compilation option to compile the following configuration
    - name: "Debian 9 release GCC 6"
      env:
        - BUILD_TYPE=Release
        - BUILD_DIR=build_deb9
        - CPACK_GENERATOR=DEB
        - DOCKER_IMAGE=sirehna/base-image-debian9-gcc6-xdyn
        - BOOST_ROOT=/opt/boost
        - SSC_ROOT=/opt/ssc

that creates this error

    268/371] Building CXX object hos/CMakeFiles/hos.dir/hos.pb.cc.o
    FAILED: hos/CMakeFiles/hos.dir/hos.pb.cc.o
    /usr/bin/c++  -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -DPROTOBUF_INLINE_NOT_IN_HEADERS=0 -I. -I../hos/inc -Ihos -I/opt/ssc/include -I../exceptions/inc -I../external_data_structures/inc -I../core/inc -I../environment_models/inc -I../yaml_parser/inc -isystem ../eigen -isystem /opt/boost/include -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-format-attribute -Wsign-compare -Wundef -Woverloaded-virtual -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -std=gnu++0x -fPIC -Wstrict-aliasing=2 -Wmissing-declarations -O3 -DNDEBUG -MD -MT hos/CMakeFiles/hos.dir/hos.pb.cc.o -MF hos/CMakeFiles/hos.dir/hos.pb.cc.o.d -o hos/CMakeFiles/hos.dir/hos.pb.cc.o -c hos/hos.pb.cc
    In file included from hos/hos.pb.cc:4:0:
    hos/hos.pb.h: In static member function 'static const HOSComs::Params* HOSComs::Params::internal_default_instance()':
    hos/hos.pb.h:227:42: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                    &_Params_default_instance_);
                                            ^
    compilation terminated due to -Wfatal-errors.
    cc1plus: all warnings being treated as errors