[hos] Removed strict-aliasing option with Mingw that creates the following error
[ 40%] Building CXX object hos/CMakeFiles/hos.dir/hos.pb.cc.obj

In file included from d:/Jenkins/jobs/XDyn_HOS/workspace/code/build/hos/hos.pb.cc:4:0:
d:/Jenkins/jobs/XDyn_HOS/workspace/code/build/hos/hos.pb.h: In static member function 'static const HOSComs::Params* HOSComs::Params::internal_default_instance()':
d:/Jenkins/jobs/XDyn_HOS/workspace/code/build/hos/hos.pb.h:223:42: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
                &_Params_default_instance_);
                                          ^
compilation terminated due to -Wfatal-errors.
cc1plus.exe: all warnings being treated as errors
make[2]: *** [hos/CMakeFiles/hos.dir/hos.pb.cc.obj] Error 1
make[1]: *** [hos/CMakeFiles/hos.dir/all] Error 2
make: *** [all] Error 2