[hdf5] Added a virtual desctructor to H5_Interface to fix a compilation problem
[ 52%] Building CXX object simulator/CMakeFiles/simulator.dir/src/SimHdf5Observer.cpp.o
In file included from /var/lib/jenkins/workspace/Simulator_TEST_BUILD_HDF5/code/simulator/src/SimHdf5Observer.cpp:14:0:
/var/lib/jenkins/workspace/Simulator_TEST_BUILD_HDF5/code/interface_hdf5/inc/h5_interface.hpp: In instantiation of class H5_Serialize<Res>:
/var/lib/jenkins/workspace/Simulator_TEST_BUILD_HDF5/code/simulator/src/SimHdf5Observer.cpp:75:35:   required from here
/var/lib/jenkins/workspace/Simulator_TEST_BUILD_HDF5/code/interface_hdf5/inc/h5_interface.hpp:53:29: error: base class class H5_Interface<Res> has a non-virtual destructor [-Werror=effc++]
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors
make[2]: *** [simulator/CMakeFiles/simulator.dir/src/SimHdf5Observer.cpp.o] Erreur 1