Fixed misleading-indentation in environment_models/src/DiracSpectralDensity.cpp
    [141/371] Building CXX object environment_models/CMakeFiles/environment_models.dir/src/DiracSpectralDensity.cpp.o
    FAILED: environment_models/CMakeFiles/environment_models.dir/src/DiracSpectralDensity.cpp.o
    /usr/local/bin/c++  -DEIGEN_DISABLE_UNALIGNED_ARRAY_ASSERT -DEIGEN_DONT_VECTORIZE -DGTEST_HAS_POSIX_RE=0 -I. -I../environment_models/inc -I/opt/ssc/include -I../exceptions/inc -I../external_data_structures/inc -isystem ../eigen -isystem /opt/boost/include -Werror -pedantic -pedantic-errors -Wextra -Wall -Wunused-function -Wunused-label -Wunused-parameter -Wunused-value -Wunused-variable -fno-common -Wformat=2 -Winit-self -Wpacked -Wp,-D_FORTIFY_SOURCE=2 -Wpointer-arith -Wmissing-declarations -Wmissing-format-attribute -Wsign-compare -Wstrict-aliasing=2 -Wundef -Wconversion -Woverloaded-virtual -Weffc++ -Wwrite-strings -Wfatal-errors -Wno-deprecated -Wvariadic-macros -fPIC -O3 -std=gnu++0x -O3 -DNDEBUG -MD -MT environment_models/CMakeFiles/environment_models.dir/src/DiracSpectralDensity.cpp.o -MF environment_models/CMakeFiles/environment_models.dir/src/DiracSpectralDensity.cpp.o.d -o environment_models/CMakeFiles/environment_models.dir/src/DiracSpectralDensity.cpp.o -c ../environment_models/src/DiracSpectralDensity.cpp
    ../environment_models/src/DiracSpectralDensity.cpp: In member function 'virtual double DiracSpectralDensity::operator()(double) const':
    ../environment_models/src/DiracSpectralDensity.cpp:39:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
         if (fabs(omega-omega0)<1E-15) return Hs*Hs/8;
         ^~
    compilation terminated due to -Wfatal-errors.