[hos] Reorder includes between protobuf and zmq to fix mingw compilation
[ 40%] Building CXX object hos/CMakeFiles/hos.dir/src/HOS.cpp.obj

In file included from c:/MinGW/x86_64-w64-mingw32/include/winsock2.h:10:0,
                 from D:/GJ/GIT/ThirdParty/libzmq_install/include/zmq.h:75,
                 from D:/GJ/GIT/ThirdParty/libzmq_install/include/zmq.hpp:43,
                 from d:/Jenkins/jobs/XDyn_HOS/workspace/code/hos/src/HOS.cpp:13:
d:/Jenkins/jobs/XDyn_HOS/workspace/code/hos/src/HOS.cpp:155:63: error: 'GetMessageA' in namespace 'HOSComs' does not name a type
         HOSComs::DataMessage wait_for_response(const HOSComs::GetMessage& message)
                                                               ^
compilation terminated due to -Wfatal-errors.
make[2]: *** [hos/CMakeFiles/hos.dir/src/HOS.cpp.obj] Error 1
make[1]: *** [hos/CMakeFiles/hos.dir/all] Error 2
make: *** [all] Error 2
Build step 'Exécuter un script shell' marked build as failure