Fixed misleading-indentation in ClosingFacetComputer.hpp
    ../mesh/inc/ClosingFacetComputer.hpp:22:5: error: this 'if' clause does not guard... [-Werror=misleading-indentation]
         if (map_or_set.find((unsigned long)idx) != map_or_set.end()) return true;
         ^~
    compilation terminated due to -Wfatal-errors.
    cc1plus: all warnings being treated as errors