Added missing link library for run_all_tests
ssc/lib/ssc/cmake/../../../include/../lib/libssc_static.a(WebSocketMessageImpl.cpp.obj):WebSocketMessageImpl.cpp:(.text+0xd3): undefined reference to `__imp_WSACleanup'
ssc/lib/ssc/cmake/../../../include/../lib/libssc_static.a(WebSocketMessageImpl.cpp.obj):WebSocketMessageImpl.cpp:(.text+0x112): undefined reference to `__imp_WSAStartup'
ssc/lib/ssc/cmake/../../../include/../lib/libssc_static.a(WebSocketMessage.cpp.obj):WebSocketMessage.cpp:(.text+0xf3): undefined reference to `__imp_WSACleanup'
ssc/lib/ssc/cmake/../../../include/../lib/libssc_static.a(WebSocketMessage.cpp.obj):WebSocketMessage.cpp:(.text+0x132): undefined reference to `__imp_WSAStartup'